declare module "goals/GoalsApp";
declare module "goals/AddGoals";
declare module "game/GameApp";
declare module "social/SocialApp";
declare module "missions/MissionsApp";
declare module "analysis/AnalysisApp";
declare module "ranking/RankingApp";
declare module "notification/App";
declare module "bank/AddBank";
