declare module "goals/GoalsApp";
declare module "goals/AddGoals";
declare module "investments/InvestmentsApp";
declare module "investments/Investment";
declare module "game/GameApp";
declare module "social/SocialApp";
declare module "missions/MissionsApp";
declare module "ranking/RankingApp";
declare module "notification/App";
